etc: cleanup DockerHelper

diff --git a/etc/DockerHelper b/etc/DockerHelper
--- a/etc/DockerHelper
+++ b/etc/DockerHelper
@@ -3,42 +3,18 @@
 set -e
 
 cd "$(dirname $(readlink -f $0))/../"
-pwd
 
 baseDir=$(pwd)
 commitSha="$(git rev-parse HEAD)"
 osList=( centos7 ubuntu20 )
 compilerList=( gcc clang )
-targetList=( base dev runner )
-
-_setup()
-{
-    if [[ $# -ne 3 ]]; then
-        echo "_setup takes 3 arguments, os, compiler and target"
-    fi
-    export DOCKER_OS="${1}"
-    export DOCKER_COMPILER="${2}"
-    export DOCKER_TARGET="${3}"
-    export DOCKER_IMAGE="openroad-${DOCKER_OS}-${DOCKER_TARGET}"
-    export DOCKER_NAME="${DOCKER_OS}-${DOCKER_COMPILER}-${commitSha}"
-    export DOCKER_FILE="docker/${DOCKER_OS}-${DOCKER_TARGET}.Dockerfile"
-    case "${DOCKER_TARGET}" in
-        "base" | "runner")
-            DOCKER_FOLDER="etc"
-            ;;
-        "dev")
-            DOCKER_FOLDER="."
-            ;;
-        *)
-            echo "Target not found"
-    esac
-}
+targetList=( base dev )
+org=openroadeda
 
 _help()
 {
     cat <<EOF
-usage: $0 create [os [target]]
-       $0 build  [os [compiler]]
+usage: $0 create [os [target [compiler]]]
        $0 test   [os [compiler]]
        $0 push   [os [target]]
        $0 help
@@ -49,69 +25,81 @@ EOF
     exit 1
 }
 
-_createContainer()
+_setup()
 {
-    echo "Create container $DOCKER_NAME"
-    if [[ -z $(docker ps -a -q -f name=${DOCKER_NAME}) ]]; then
-        docker container create -it -w /OpenROAD --name=${DOCKER_NAME} ${DOCKER_IMAGE}
+    if [[ $# -ne 3 ]]; then
+        echo "_setup takes 3 arguments:"
+        echo "_setup os compiler target"
+        exit 1
     fi
-}
-
-_build()
-{
-    _setup "${1:-centos7}" "${2:-gcc}" "base"
-    echo "Build app on $DOCKER_NAME with $DOCKER_COMPILER"
-    _createContainer
-    docker container start "${DOCKER_NAME}"
-    docker exec "${DOCKER_NAME}" "rm -rf /OpenROAD/*"
-    docker cp "${baseDir}/." "${DOCKER_NAME}":/OpenROAD/.
-    docker exec "${DOCKER_NAME}" ./etc/BuildHelper "${DOCKER_COMPILER}"
-    docker container stop "${DOCKER_NAME}"
+    os="${1}"
+    compiler="${2}"
+    target="${3}"
+    file="docker/Dockerfile.${target}"
+    case "${target}" in
+        "base" )
+            case "${os}" in
+                "centos7")
+                    fromImage="centos:centos7"
+                    ;;
+                "ubuntu20")
+                    fromImage="ubuntu:20.04"
+                    ;;
+                *)
+                    echo "Target OS=${os} not supported"
+                    _help
+                    ;;
+            esac
+            context="etc"
+            imageTag="${org}/${os}-${target}"
+            buildArgs="--build-arg fromImage=${fromImage}"
+            ;;
+        "dev" )
+            fromImage="${org}/${os}-base"
+            context="."
+            imageTag="${org}/${os}-${compiler}-${commitSha}"
+            buildArgs="--build-arg fromImage=${fromImage} --build-arg compiler=${compiler}"
+            ;;
+        *)
+            echo "Target ${target} not found"
+            _help
+    esac
 }
 
 _test()
 {
-    _setup "${1:-centos7}" "${2:-gcc}" "base"
-    echo "Run regression test on $DOCKER_NAME with $DOCKER_COMPILER"
-    _createContainer
-    docker container start "${DOCKER_NAME}"
-    docker exec "${DOCKER_NAME}" "./test/regression"
-    docker container stop "${DOCKER_NAME}"
+    _setup "${1:-centos7}" "${2:-gcc}" "dev"
+    # create image with compiled binary if it does not exists
+    if [[ $(docker images -q ${imageTag}) == "" ]]; then
+        _create "${1:-centos7}" "dev" "${2:-gcc}"
+    fi
+    echo "Run regression test on ${imageTag}"
+    docker run --rm -it "${imageTag}" "./test/regression"
 }
 
 _create()
 {
-    _setup "${1:-centos7}" "NONE" "${2:-base}"
-    echo "Create docker image $DOCKER_IMAGE using $DOCKER_FILE with target $DOCKER_TARGET"
-    docker build -f "${DOCKER_FILE}" --tag "${DOCKER_IMAGE}" "${DOCKER_FOLDER}"
+    _setup "${1:-centos7}" "${3:-gcc}" "${2:-base}"
+    echo "Create docker image ${imageTag} using ${file}"
+    docker build --file "${file}" --tag "${imageTag}" ${buildArgs} "${context}"
 }
 
 _push()
 {
     _setup "${1:-centos7}" "NONE" "${2:-base}"
-    echo "Push docker image $DOCKER_IMAGE to DockerHub [NOT IMPLEMENTED YET]"
+    echo "Push docker image ${imageTag} to DockerHub [NOT IMPLEMENTED YET]"
 }
 
-_all()
-{
-    _create
-    _build
-    _test
-    _push
-}
-
-_rule="${1:-all}"
-if [[ $# -gt 0 ]]; then
-    shift 1
-fi
-
+# script has at most 3 arguments
 if [[ $# -gt 3 ]]; then
     _help
 fi
 
+# check if the main rule is valid
 if [[ -z $(command -v "_${_rule}") ]]; then
     echo "Command $_rule not found"
     _help
 else
-    "_${_rule}" ${@} || _help
+    # call rule with arguments
+    "_${_rule}" ${@}
 fi
