grt: move to ctest
Signed-off-by: Peter Gadfort <peter.gadfort@gmail.com>

diff --git a/src/grt/test/save_guideok b/src/grt/test/save_guideok
--- a/src/grt/test/save_guideok
+++ b/src/grt/test/save_guideok
@@ -1,13 +1,11 @@
-#!/bin/sh
-# The next line is executed by /bin/sh, but not Tcl \
-exec tclsh $0 ${1+"$@"}
+#!/usr/bin/env bash
 
-###############################################################################
+############################################################################
+##
+## Copyright (c) 2024, The Regents of the University of California
+## All rights reserved.
 ##
 ## BSD 3-Clause License
-##
-## Copyright (c) 2019, Parallax Software, Inc.
-## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
 ## modification, are permitted provided that the following conditions are met:
@@ -17,7 +15,7 @@ exec tclsh $0 ${1+"$@"}
 ##
 ## * Redistributions in binary form must reproduce the above copyright notice,
 ##   this list of conditions and the following disclaimer in the documentation
-##   and#or other materials provided with the distribution.
+##   and/or other materials provided with the distribution.
 ##
 ## * Neither the name of the copyright holder nor the names of its
 ##   contributors may be used to endorse or promote products derived from
@@ -35,60 +33,19 @@ exec tclsh $0 ${1+"$@"}
 ## ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 ## POSSIBILITY OF SUCH DAMAGE.
 ##
-###############################################################################
+############################################################################
 
-# Usage: save_guideok test1 [test2...] | failures
-# Where test1 is all or the name of a tcl script in /test
-# Wildcard matching with '*' and '?' in test names is supported.
+set -e
 
-# Directory containing tests.
-set test_dir [file dirname [file normalize [info script]]]
-set openroad_dir [file dirname [file dirname [file dirname $test_dir]]]
-
-source [file join $openroad_dir "test" "regression.tcl"]
-source [file join $test_dir "regression_tests.tcl"]
-
-proc save_guideok_main {} {
-  global argv
-  if { $argv == "help" || $argv == "-help" } {
-    puts {Usage: save_guideok [failures] test1 [test2]...}
-  } else {
-    if { $argv == "failures" } {
-      set tests [failed_tests]
-    } else {
-      set tests $argv
-    }
-    foreach test $tests {
-      if { [lsearch [group_tests "all"] $test] == -1 } {
-        puts "Error: test $test not found."
-      } else {
-        save_guideok $test
-      }
-    }
-  }
-}
-
-proc save_guideok { test } {
-  set guideok_file [test_guideok_file $test]
-  set guide_file [test_guide_result_file $test]
-  if { [file exists $guide_file] } {
-    file copy -force $guide_file $guideok_file
-  }
-}
-
-proc test_guideok_file { test } {
-  global test_dir
-  return [file join $test_dir "$test.guideok"]
-}
-
-proc test_guide_result_file { test } {
-  global result_dir
-  set lang [result_lang $test]
-  return [file join $result_dir "$test-$lang.guide"]
-}
-
-save_guideok_main
-
-# Local Variables:
-# mode:tcl
-# End:
+for test_name in "${@:1}"
+do
+    if [ -f "results/${test_name}-tcl.guide" ]; then
+        cp "results/${test_name}-tcl.guide" "${test_name}.guideok"
+        echo "${test_name}"
+    elif [ -f "results/${test_name}-py.guide" ]; then
+        cp "results/${test_name}-py.guide" "${test_name}.guideok"
+        echo "${test_name}"
+    else
+        echo "\"${test_name}\" guide file not found"
+    fi
+done
